apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: project-quay
  namespace: openshift-operators
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: project-quay
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace