id = "fast-datapath"
name = "Fast Datapath for RHEL 9"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/fast-datapath/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true
