id = "rhocp-4.14"
name = "Red Hat OpenShift Container Platform 4.14 for RHEL 9"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/rhocp/4.14/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true
