log_level: warn
indexer:
  connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
  scanlock_retry: 11
  layer_scan_concurrency: 6
  migrations: true
matcher:
  connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
  migrations: true
  #      max_conn_pool: 100
      #  run: ""
  #      indexer_addr: clair-indexer
notifier:
  connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
  migrations: true
  delivery_interval: 1m
  poll_interval: 5m
auth:
  psk:
    #    key: "MTU5YzA4Y2ZkNzJoMQ=="
    key: "aTZlNzZhZTZnN2YzYw=="
    iss: ["quay"]
  # tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    #    agent_endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"