apiVersion: v1
kind: Secret
metadata:
  name: homelab-clair-config-bundle-secret
  namespace: quay
stringData:
  config.yaml: |
    http_listen_addr: :8081
    introspection_addr: :8089
    log_level: warn
    indexer:
    connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
    scanlock_retry: 10
    layer_scan_concurrency: 5
    migrations: true
    matcher:
    connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
    max_conn_pool: 100
        #  run: ""
    migrations: true
    indexer_addr: clair-indexer
    notifier:
    connstring: host=postgres.revoweb.home port=5432 dbname=clair user=clairuser password=clairpass-gp7tm4k sslmode=disable
    delivery_interval: 1m
    poll_interval: 5m
    migrations: true
    auth:
    psk:
        #    key: "MTU5YzA4Y2ZkNzJoMQ=="
        key: "aTZlNzZhZTZnN2YzYw=="
        iss: ["quay"]
    # tracing and metrics
    trace:
    name: "jaeger"
    probability: 1
    jaeger:
        #    agent_endpoint: "localhost:6831"
        service_name: "clair"
    metrics:
    name: "prometheus"