apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-homelab
  namespace: quay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quay-homelab
  template:
    metadata:
      labels:
        app: quay-homelab
    spec:
      containers:
      - name: quay-homelab-clairv4
        image: registry.redhat.io/quay/clair-rhel8:v3.11
        ports:
        - containerPort: 80
      - name: quay-homelab-quay
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 80
