apiVersion: v1
kind: Secret
metadata:
  name: homelab-quay-config-bundle-secret
  namespace: quay
stringData:
  config.yaml: |
    AUTHENTICATION_TYPE: LDAP
    AVATAR_KIND: local
    BUILDLOGS_REDIS:
        host: redis.revoweb.home
        password: redis-thegp7tm4k
        port: 6379
    DATABASE_SECRET_KEY: 7be1db27-1a4d-4878-ac28-8913a0365ea6
    DB_CONNECTION_ARGS: {}
    DB_URI: postgresql://quayuser:quaypass-gp7tm4k@postgres.revoweb.home/quay
    DEFAULT_TAG_EXPIRATION: 2w
    DISTRIBUTED_STORAGE_CONFIG:
        default:
            - LocalStorage
            - storage_path: /datastorage/registry
        s3Storage:
            - S3Storage
            - host: s3.us-west-001.backblazeb2.com
              s3_access_key: 001bb7e92a90a09000000000c
              s3_secret_key: K00145Apw57j69xMtaI6iDkvXs9ybmg
              s3_bucket: nrevo-quay-bucket
              storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
        - default
    EXTERNAL_TLS_TERMINATION: true
    FEATURE_ACI_CONVERSION: false
    FEATURE_ACTION_LOG_ROTATION: false
    FEATURE_ANONYMOUS_ACCESS: true
    FEATURE_APP_REGISTRY: true
    FEATURE_APP_SPECIFIC_TOKENS: true
    FEATURE_BITBUCKET_BUILD: false
    FEATURE_BLACKLISTED_EMAILS: false
    FEATURE_BUILD_SUPPORT: false
    FEATURE_CHANGE_TAG_EXPIRATION: true
    FEATURE_DIRECT_LOGIN: true
    FEATURE_EXTENDED_REPOSITORY_NAMES: true
    FEATURE_FIPS: false
    FEATURE_GENERAL_OCI_SUPPORT: true
    FEATURE_GITHUB_BUILD: false
    FEATURE_GITHUB_LOGIN: false
    FEATURE_GITLAB_BUILD: false
    FEATURE_GOOGLE_LOGIN: false
    FEATURE_INVITE_ONLY_USER_CREATION: false
    FEATURE_MAILING: false
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true
    FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
    FEATURE_PROXY_CACHE: true
    FEATURE_PROXY_STORAGE: false
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_REPO_MIRROR: true
    FEATURE_REQUIRE_TEAM_INVITE: true
    FEATURE_RESTRICTED_V1_PUSH: true
    FEATURE_SECURITY_NOTIFICATIONS: false
    FEATURE_SECURITY_SCANNER: true
    FEATURE_STORAGE_REPLICATION: false
    FEATURE_TEAM_SYNCING: true
    FEATURE_USER_CREATION: true
    FEATURE_USER_LAST_ACCESSED: true
    FEATURE_USER_LOG_ACCESS: false
    FEATURE_USER_METADATA: false
    FEATURE_USER_RENAME: false
    FEATURE_USERNAME_CONFIRMATION: true
    FRESH_LOGIN_TIMEOUT: 10m
    GITHUB_LOGIN_CONFIG: {}
    GITHUB_TRIGGER_CONFIG: {}
    GITLAB_TRIGGER_KIND: {}
    LDAP_ADMIN_DN: uid=bindserviceaccount,cn=sysaccounts,cn=etc,dc=revoweb,dc=home
    LDAP_ADMIN_PASSWD: bind-gp7tm4k
    LDAP_ALLOW_INSECURE_FALLBACK: true
    LDAP_BASE_DN:
        - dc=revoweb
        - dc=home
    LDAP_EMAIL_ATTR: mail
    LDAP_SECONDARY_USER_RDNS:
        - cn=groups,cn=accounts
    LDAP_UID_ATTR: uid
    LDAP_URI: ldap://ipa.revoweb.home
    LDAP_USER_FILTER: (memberOf=cn=quay,cn=groups,cn=accounts,dc=revoweb,dc=home)
    LDAP_USER_RDN:
        - cn=users
        - cn=accounts
    LOG_ARCHIVE_LOCATION: default
    LOGS_MODEL: database
    LOGS_MODEL_CONFIG: {}
    MAIL_DEFAULT_SENDER: support@quay.io
    MAIL_PORT: 587
    MAIL_USE_AUTH: false
    MAIL_USE_TLS: false
    PREFERRED_URL_SCHEME: https
    REGISTRY_TITLE: Revo Registry
    REGISTRY_TITLE_SHORT: Revo Registry
    REPO_MIRROR_INTERVAL: 30
    REPO_MIRROR_TLS_VERIFY: true
    SEARCH_MAX_RESULT_PAGE_COUNT: 10
    SEARCH_RESULTS_PER_PAGE: 10
    SECRET_KEY: 21735ac7-a4c1-4628-9aad-6ff4fab29a29
    SECURITY_SCANNER_INDEXING_INTERVAL: 30
    SECURITY_SCANNER_V4_ENDPOINT: http://localhost:8081
    SECURITY_SCANNER_V4_PSK: aTZlNzZhZTZnN2YzYw==
    SERVER_HOSTNAME: quay.revoweb.com
    SETUP_COMPLETE: true
    SUPER_USERS:
        - quayadmin
        - admin
    TAG_EXPIRATION_OPTIONS:
        - 0s
        - 1d
        - 1w
        - 2w
        - 4w
    TEAM_RESYNC_STALE_TIME: 30m
    TESTING: false
    USE_CDN: false
    USER_EVENTS_REDIS:
        host: redis.revoweb.home
        password: redis-thegp7tm4k
        port: 6379
    USER_RECOVERY_TOKEN_LIFETIME: 30m
    USERFILES_LOCATION: default